package ua.training.entrance_examination.constants;

public interface GlobalConstants {

	int BIOLOGISTS_NUMBER = 200;
	int MATHEMATICIANS_NUMBER = 250;

	int MIN_QUEUE_THRESHOLD = 25;
	int MAX_QUEUE_THRESHOLD = 50;

	int MIN_UNIVERSAL_UNIVERSITY_DOCUMENTS_NUM = 1;
	int MAX_UNIVERSAL_UNIVERSITY_DOCUMENTS_NUM = 5;

	int CONSUMER_THREAD_SLEEP_BEFORE_FILLING_MSEC = 5;
	
	int CONSUMER_THREAD_SLEEP_BEFORE_UNIVERSAL_UNIVERSITY_MSEC = 7;
	int CONSUMER_THREAD_SLEEP_BEFORE_POLYTECHNICAL_UNIVERSITY_MSEC = 10;
	int CONSUMER_THREAD_SLEEP_BEFORE_MEDICAL_UNIVERSITY_MSEC = 5;

}
